# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interfaz3.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
sys.path.append('../')
from PyQt5 import QtCore, QtGui, QtWidgets
from BaseDeDatos.CapaConexion import *


class Ui_RegistrarVentaDeEntradas(object):

    def mostrarDetalles(self):
        detalle = obtenerDetalles()
        tipo_entrada = detalle[0]
        tipo_visita = detalle[1]
        monto = detalle[2]
        guia = detalle[3]
        if guia:
            guia = "Si"
        else:
            guia = "No"
        cantidad = detalle[5]
        total = detalle[4]
        rowPosition = self.tableWidget.rowCount()
        self.tableWidget.insertRow(rowPosition)
        self.tableWidget.setItem(rowPosition , 0, QtWidgets.QTableWidgetItem(tipo_entrada))
        self.tableWidget.setItem(rowPosition , 1, QtWidgets.QTableWidgetItem(tipo_visita))
        self.tableWidget.setItem(rowPosition , 2, QtWidgets.QTableWidgetItem(guia))
        self.tableWidget.setItem(rowPosition , 3, QtWidgets.QTableWidgetItem(str(cantidad)))
        self.tableWidget.setItem(rowPosition , 4, QtWidgets.QTableWidgetItem(str(monto)))
        self.tableWidget.setItem(rowPosition , 5, QtWidgets.QTableWidgetItem(str(total)))

    def setupUi(self, RegistrarVentaDeEntradas):
        RegistrarVentaDeEntradas.setObjectName("RegistrarVentaDeEntradas")
        RegistrarVentaDeEntradas.setEnabled(True)
        RegistrarVentaDeEntradas.resize(695, 340)
        RegistrarVentaDeEntradas.setMinimumSize(QtCore.QSize(695, 340))
        RegistrarVentaDeEntradas.setMaximumSize(QtCore.QSize(695, 340))
        self.tableWidget = QtWidgets.QTableWidget(RegistrarVentaDeEntradas)
        self.tableWidget.setEnabled(True)
        self.tableWidget.setGeometry(QtCore.QRect(30, 40, 631, 211))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.btn_confirmar = QtWidgets.QPushButton(RegistrarVentaDeEntradas)
        self.btn_confirmar.setGeometry(QtCore.QRect(250, 300, 75, 23))
        self.btn_confirmar.setObjectName("btn_confirmar")
        self.btn_cancelar = QtWidgets.QPushButton(RegistrarVentaDeEntradas)
        self.btn_cancelar.setGeometry(QtCore.QRect(340, 300, 75, 23))
        self.btn_cancelar.setObjectName("btn_cancelar")
        self.btn_mostrar_detalles = QtWidgets.QPushButton(RegistrarVentaDeEntradas)
        self.btn_mostrar_detalles.setGeometry(QtCore.QRect(30, 260, 101, 23))
        self.btn_mostrar_detalles.setObjectName("btn_mostrar_detalles")
        self.btn_mostrar_detalles.clicked.connect(self.mostrarDetalles)

        self.retranslateUi(RegistrarVentaDeEntradas)
        self.btn_cancelar.clicked.connect(RegistrarVentaDeEntradas.reject)
        QtCore.QMetaObject.connectSlotsByName(RegistrarVentaDeEntradas)

    def retranslateUi(self, RegistrarVentaDeEntradas):
        _translate = QtCore.QCoreApplication.translate
        RegistrarVentaDeEntradas.setWindowTitle(_translate("RegistrarVentaDeEntradas", "Registrar venta de entradas"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("RegistrarVentaDeEntradas", "Tipo entrada"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("RegistrarVentaDeEntradas", "Tipo visita"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("RegistrarVentaDeEntradas", "Guia"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("RegistrarVentaDeEntradas", "Cantidad"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("RegistrarVentaDeEntradas", "Precio"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("RegistrarVentaDeEntradas", "Total"))
        self.btn_confirmar.setText(_translate("RegistrarVentaDeEntradas", "Confirmar"))
        self.btn_cancelar.setText(_translate("RegistrarVentaDeEntradas", "Cancelar"))
        self.btn_mostrar_detalles.setText(_translate("RegistrarVentaDeEntradas", "Mostrar detalles"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RegistrarVentaDeEntradas = QtWidgets.QDialog()
    ui = Ui_RegistrarVentaDeEntradas()
    ui.setupUi(RegistrarVentaDeEntradas)
    RegistrarVentaDeEntradas.show()
    sys.exit(app.exec_())
