/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.0 		*/
/*  Created On : 23-may.-2021 00:17:10 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[cambioEstado]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [dbo].[cambioEstado]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[detalleExposicion]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [dbo].[detalleExposicion]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[empleado]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [dbo].[empleado]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[entrada]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [dbo].[entrada]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[estado]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [dbo].[estado]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[exposicion]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [dbo].[exposicion]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[gestorVentaEntrada]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [dbo].[gestorVentaEntrada]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[impresorEntrada]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [dbo].[impresorEntrada]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[obra]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [dbo].[obra]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[pantallaCantActualSede]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [dbo].[pantallaCantActualSede]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[pantallaCantidadActualPrinci]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [dbo].[pantallaCantidadActualPrinci]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[pantallaVentaEntradas]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [dbo].[pantallaVentaEntradas]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[reservaVisita]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [dbo].[reservaVisita]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[sede]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [dbo].[sede]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[sesion]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [dbo].[sesion]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[tarifa]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [dbo].[tarifa]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[tipoEntrada]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [dbo].[tipoEntrada]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[tipoVisita]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [dbo].[tipoVisita]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[usuario]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [dbo].[usuario]
GO

/* Create Tables */

CREATE TABLE [dbo].[cambioEstado]
(
	[estado] varchar(50) NULL,
	[fechaHoraFin] datetime NULL,
	[fechaHoraInicio] datetime NULL
)
GO

CREATE TABLE [dbo].[detalleExposicion]
(
	[lugarAsignado] varchar(50) NULL,
	[obra] varchar(50) NULL,
	[operaciones] varchar(50) NULL
)
GO

CREATE TABLE [dbo].[empleado]
(
	[nombre] varchar(50) NULL,
	[apellido] varchar(50) NULL,
	[codigoValidacion] int NOT NULL,
	[cuit] varchar(50) NULL,
	[dni] varchar(50) NULL,
	[domicilio] varchar(50) NULL,
	[fechaDeIngreso] date NULL,
	[fechaNacimiento] date NULL,
	[mail] varchar(50) NULL,
	[sedeDondeTrabaja] varchar(50) NOT NULL,
	[sexo] varchar(50) NULL,
	[telefono] varchar(50) NULL
)
GO

CREATE TABLE [dbo].[entrada]
(
	[fechaVenta] date NULL,
	[horaVenta] time(7) NULL,
	[monto] float NULL,
	[numero] int NULL
)
GO

CREATE TABLE [dbo].[estado]
(
	[nombre] varchar(50) NULL,
	[ambito] varchar(50) NULL,
	[descripcion] varchar(50) NULL,
	[estadoReserva] varchar(50) NULL
)
GO

CREATE TABLE [dbo].[exposicion]
(
	[nombre] varchar(50) NULL,
	[detalleExposicion] varchar(50) NULL,
	[fechaFin] date NULL,
	[fechaFinReplanificada] date NULL,
	[fechaInicio] date NULL,
	[fechaInicioReplanificada] date NULL,
	[horaApertura] time(7) NULL,
	[horaCierre] time(7) NULL
)
GO

CREATE TABLE [dbo].[gestorVentaEntrada]
(
	[cantidadEntradasEmitir] varchar(50) NULL,
	[capacidadMaximaSede] varchar(50) NULL,
	[confirmacionVenta] binary(50) NULL,
	[duracionEstimada] varchar(50) NULL,
	[empleado] varchar(50) NOT NULL,
	[fechaHoraActual] datetime NULL,
	[hayGuia] binary(50) NULL,
	[montoTotalAPagar] float NULL,
	[numeroEntrada] varchar(50) NULL,
	[sedeActual] varchar(50) NOT NULL,
	[tipoEntrada] varchar(50) NOT NULL,
	[tipoVisita] varchar(50) NOT NULL
)
GO

CREATE TABLE [dbo].[impresorEntrada]
(
	[detalleEntrad] varchar(50) NULL
)
GO

CREATE TABLE [dbo].[obra]
(
	[nombreObra] varchar(50) NOT NULL,
	[alto] int NULL,
	[ancho] int NULL,
	[codigoSensor] int NULL,
	[descripcion] varchar(50) NULL,
	[duracionExtendida] time(7) NULL,
	[duracionResumida] time(7) NULL,
	[fechaCreacion] date NULL,
	[fechaPrimerIngreso] date NULL,
	[peso] float NULL,
	[valuacion] float NULL
)
GO

CREATE TABLE [dbo].[pantallaCantActualSede]
(
	[cantidadActual] varchar(50) NULL,
	[nombreSala] varchar(50) NULL
)
GO

CREATE TABLE [dbo].[pantallaCantidadActualPrinci]
(
	[cantidadActual] varchar(50) NULL,
	[capacidadTotal] varchar(50) NULL
)
GO

CREATE TABLE [dbo].[pantallaVentaEntradas]
(
	[regitrarVenta] binary(50) NULL,
	[seleccionNroEntradas] int NULL,
	[confirmacionVenta] binary(50) NULL,
	[tipoEntrada] varchar(50) NULL,
	[tipoVisita] varchar(50) NULL,
	[detalleVenta] varchar(50) NULL,
	[montoTarifas] float NULL,
	[tarifas] varchar(50) NULL,
	[ventanaHabilitada] varchar(50) NULL
)
GO

CREATE TABLE [dbo].[reservaVisita]
(
	[cantidadAlumnos] int NULL,
	[cantidadAlumnosConfirmada] int NULL,
	[duracionEstimada] time(7) NULL,
	[fechaHoraCreacion] date NULL,
	[fechaHoraReserva] date NULL,
	[horaFinReal] time(7) NULL,
	[horaInicioReal] time(7) NULL,
	[numeroReserva] int NOT NULL
)
GO

CREATE TABLE [dbo].[sede]
(
	[cantidadMaximaPorGuia] int NULL,
	[cantidadMaximaVisitantes] int NULL,
	[duracionExposicionesVigentes] time(7) NULL,
	[nombre] varchar(50) NULL,
	[reservaVisita] varchar(50) NULL,
	[tarifasVigentes] varchar(50) NULL
)
GO

CREATE TABLE [dbo].[sesion]
(
	[empleadoSesion] varchar(50) NOT NULL,
	[fechaFin] date NULL,
	[fechaInicio] date NULL,
	[horaFin] time(7) NULL,
	[horaInicio] time(7) NULL
)
GO

CREATE TABLE [dbo].[tarifa]
(
	[fechaFinVigencia] time(7) NULL,
	[fechaInicioVigencia] time(7) NULL,
	[monto] float NULL,
	[montoAdicionalGuia] float NULL,
	[tipoVisita] varchar(50) NOT NULL,
	[tipoDeEntrada] varchar(50) NOT NULL
)
GO

CREATE TABLE [dbo].[tipoEntrada]
(
	[nombre] varchar(50) NULL,
	[tipoVisita] varchar(50) NULL
)
GO

CREATE TABLE [dbo].[tipoVisita]
(
	[nombre] varchar(50) NULL,
	[tipoVisita] varchar(50) NULL
)
GO

CREATE TABLE [dbo].[usuario]
(
	[caducidad] varchar(50) NULL,
	[contraseña] varchar(50) NULL,
	[nombre] varchar(50) NULL,
	[usuarioLogueado] varchar(50) NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [dbo].[empleado] 
 ADD CONSTRAINT [PK_empleado]
	PRIMARY KEY CLUSTERED ([sedeDondeTrabaja] ASC,[codigoValidacion] ASC)
GO

ALTER TABLE [dbo].[gestorVentaEntrada] 
 ADD CONSTRAINT [PK_gestorVentaEntrada]
	PRIMARY KEY CLUSTERED ([sedeActual] ASC,[tipoEntrada] ASC,[tipoVisita] ASC)
GO

ALTER TABLE [dbo].[obra] 
 ADD CONSTRAINT [PK_obra]
	PRIMARY KEY CLUSTERED ([nombreObra] ASC)
GO

ALTER TABLE [dbo].[reservaVisita] 
 ADD CONSTRAINT [PK_reservaVisita]
	PRIMARY KEY CLUSTERED ([numeroReserva] ASC)
GO

ALTER TABLE [dbo].[sesion] 
 ADD CONSTRAINT [PK_sesion]
	PRIMARY KEY CLUSTERED ([empleadoSesion] ASC)
GO

ALTER TABLE [dbo].[tarifa] 
 ADD CONSTRAINT [PK_tarifa]
	PRIMARY KEY CLUSTERED ([tipoVisita] ASC,[tipoDeEntrada] ASC)
GO
